GameArea.js
components/BadCloud.js

Made a component for bad cloud and rendering it at a static position.
To do: Make the cloud move down. Make logic for randomly spawning cloud. Randomize the cloud picture.

Component for bad cloud and rendering it

---

GameArea.js
Physics.js

Made a Physics.js file and using it in the GameEngine tag in GameArea. Made simple logic for making only one cloud fall.

Falling cloud

---

GameArea.js
systems/BadCloudPhysics.js
systems/index.js
systems/physics.js

- Made a folder named 'systems'
- The 'physics' file inside it adds the physics engine to the whole game and should never be changed
- The 'BadCloudPhysics' file inside it contains all the physics for the bad cloud
- The 'index' file inside it exports the physics engine and the bad cloud physics. This is where we will export all the different physics.
- The "systems={Systems}" inside the GameEngine tag in the GameArea file automatically checks for the index.js file inside the systems folder.

Broke out physics for bad cloud

---

systems/FlowerPhysics.js

-Changed function that makes flower move from touches type "press" to type "move"
-This makes flower move by sliding finger across the screen

flower moves when sliding across the screen

---

GameArea.js
systems/BadCloudPhysics.js

- Moved the rendering of the clouds from GameArea into a function in BadCloudPhysics
- For now, the clouds will start spawning when you touch the screen the first time
- When a cloud disappears from the screen, it's removed and a new one is spawned
- For now, it's always three clouds on the screen

Spawn bad clouds randomly

---

systems/FlowerPhysics.js

Made two more checks in the function that moves the flower (x-pos) so that the flower won't run outside of the screen. Now at last in the function, we return the flowers x-pos.

Flower stays in screen

---

assets/Images.js
components/Flower.js
components/Grass.js
components/Pot.js

Added images: flower, pot, grass, background to new Images.js file and imported them in the relevant files with the new source.

Images to new images.js file

---

systems/BadCloudPhysics.js
systems/FlowerPhysics.js
systems/GroundPhysics.js
systems/index.js

-Made file GroundPhysics.js for the movement of the grass and the pot. 
-Made function so that the ground starts to move down when game has started.

Pot and grass move down

---

GameArea.js
components/WaterMeter.js

-Made component for the WaterMeter and rendered it in the gameArea.
-Added some styling to it.

Water meter component

---

GameArea.js
systems/FlowerPhysics.js

-Made changes in flower-movement-function so that the location of the touch/finger checks whether it's on the left or right side of the flower's position instead of the screen's left/right side. 
-This made the flower movement much smoother. 
-Also changed the "else if" in the function, because that made the flower "vibrate" when the touch position was close to the flower position.
-At last, changed the speed of the movement to -10/+10.

Flower movement

---

systems/BadCloudPhysics.js

Changed BadCloudPhysics so that four clouds are spawning after 2 sec instead of after touch on screen.

Make clouds fall after a set time

---

GameArea.js
components/Flower.js

-Hitbox bug in progress
-Flower made to circle

Hit box not centered

---

GameArea.js
components/GoodCloud.js
systems/BadCloudPhysics.js
systems/GoodCloudPhysics.js
systems/index.js

Made a goodCloud component and rendering it in a goodCloudPhysics, almost exactly as the badClooudPhysics. Also cleaned up some messy code.

GoodCloud and its physics, cleaned up code.

---

systems/FlowerPhysics.js

Checking the t.delta.pageX in FlowerPhysics (that returns a positive or negative value depending on where you touch the screen) and translating the flower depending on that instead of setting its position.

Translating the flower instead of setPosition

---

GameArea.js
systems/FlowerPhysics.js

Flower translating up from pot for 2 seconds.

Flower grow up at start

---

GameArea.js
assets/Images.js
components/Flower.js
components/WaterMeter.js
systems/BadCloudPhysics.js
systems/FlowerPhysics.js
systems/WaterMeterPhysics.js

Passing a flowerNumber prop to the flower. Changing that prop inside FlowerPhysics depending on the hits inside "collisionStart" and the waterLevel inside "collisionEnd".  The waterMeter is now rendered in GameArea, and has a waterLevel prop and a newWaterMeterY prop that is changed on collision inside WaterMeterPhysics.

Change face of flower

---

GameArea.js
components/GameOverScreen.js

Passing the time as the score to game over screen

Correct score on game over screen

---

systems/BeePhysics.js

Randomizing the number of pixels the bee should move on the Y axes between 1 and 5, so that it looks like it's buzzing.

Random if the bee should move on Y by 1 or 5.

---

systems/BeePhysics.js

-Made check for when bee is dead and added translation.
-Removed check for if bee is not dead for the gravity so that the bee is affected by the gravity even when it falls dead

Bee Moves with translation and gravity also when dead

---

.expo-shared/README.md
app.json

Test publish expo

---

components/GameOverScreen.js
components/StartScreen.js

-Changed the styling of the start screen and game over screen. 
-Created a design that is more like the design of start- and game over screen in the original FlowerGrow.

Styling game over start screen

---

GameArea.js

removed unnecessary code from muteAllSound function

removed unnecessary code

---

GameArea.js
systems/BeePhysics.js

Spawning one more bee at around 40 sec. Added more possible starting points for bee to randomize between. Removed sound from bee.

Spawn more bees without sound
